version: '3'
services:
  adt-service:
    image: 'ampathke/amrs-adt:latest'
    env_file: 
      - .env
    restart: always
    ports:
        - '3000:3000'
    volumes: 
        - ./.env:/packages/adt/.env